.TH DITHDS 1
.SH NAME
dithds \- ditroff previewer for HDS200 graphics terminals
.SH SYNOPSIS
.B dithds
[
.BI \-p n
]
{
file
}
.SH DESCRIPTION
.I Dithds
allows previewing of
.IR ditroff (1)
output on the HDS200 graphics series graphic display terminals.
.PP
Commands:
.PP
To get to the next page wait for the bell then type carriage return.
To get to an absolute page, type the number and a carriage return
after the bell.
To move to a relative page type + or \- followed by the page difference. 
Thus +4 will move 4 pages forward.
4 will move to page 4.
Remember to follow these with a carriage return.
.PP
On the last page a carriage return will exit the program.
On any page a 'q' will terminate the program.
To review all possible commands type '?'.
.PP
Specifying the
.BI \-p n
option will cause
.I dithds
to start on page number
.IR n .
The default is 1.
.SH BUGS
None known.
Please feel free to make additions and corrections.
If you make changes please ship a copy off to me,
ihnp4!uiucdcs!uiucme!slaney (slaney%uiucme@a.cs.uiuc.edu (ARPAnet)).
.SH NOTES
.I Ditroff
can be output to any of the following HDS200 graphics terminals:  
.IP
200, 201.
.PP
The features of this program are:
.IP
Complete device independence. 
All output from ditroff is capable of being processed independent
of what device it was intended for.
Naturally somethings aren't perfect.
That's why this is called a previewer.
It is not intended for publications purposes. 
Only to give a good indication of correct form.
It provides a very convenient method of checking for orphans
and widows (lines).  
.IP
Character point size mapping.
.IP
Italic font is emulated using the terminals slanted character mode.
.IP
Currently only straight line drawing.
The routine for arcs/circles is in the library included but
draws circles starting from the right and proceeding counterclockwise. 
.I Ditroff
likes it from the left.
It may take some playing with.
.IP
Character slant is also possible.
The slant routine is included in dithds.lib.c.
Needs to be played with (see again the BUGS section).
.IP
Complete forward and backward paging.
.SH IMPROVEMENTS
Areas lacking for this program are:
.IP
circles
.sp
character slant
.sp
spline fits
.sp
some special characters
.SH AUTHOR
Jeff Slaney November 1985, helped by Philip Gross -- Tek41xx version.
Vincent R. Slyngstad June 1987 -- Mods for HDS terminals.
