/* User commands */
#define LEFT 'h'
#define RIGHT 'l'
#define UPWARD 'k'
#define DOWN 'j'
#define FIRE ' '
#define UPRIGHT 'u'
#define UPLEFT 'y'
#define DOWNRIGHT 'n'
#define DOWNLEFT 'b'
#define FASTLEFT 'H'
#define FASTRIGHT 'L'
#define PAUSEKEY '\t'
