#! /bin/sh
# ihave - stub for unimplemented I-have/send-me protocol
NEWSCTL=${NEWSCTL-/usr/lib/news}; export NEWSCTL
NEWSBIN=${NEWSBIN-/usr/lib/newsbin}; export NEWSBIN
NEWSARTS=${NEWSARTS-/usr/spool/news}; export NEWSARTS
PATH=$NEWSCTL:$NEWSBIN:/bin:/usr/bin; export PATH

SENDER="`newsreply`"
echo I-have/send-me not implemented | mail "$SENDER"
