.TH UUREC 8
.SH NAME
uurec \- receive news articles via mail
.SH SYNOPSIS
.B /usr/lib/news/uurec
.SH DESCRIPTION
.I uurec
reads news articles from standard input sent by
.IR uusend (8),
decodes them, and gives each article to
.IR postnews (1)
for insertion.
.SH SEE ALSO
postnews(1), readnews(1),
uusend(8).
