.TH FLIBS 6 "28 October 1985" "" "FLIBS"
.SH NAME
flibs - Evolving state machines
.SH SYNOPSIS
flibs
.SH DESCRIPTION
.I FLIBS
is an implementation of the evolving program that A.K.Dewdney wrote 
about in his November 1985 Scientific American column "Computer 
Recreations".  For more information, read the article, read the source 
code, or play the game.
.PP
The game itself includes full instructions.
.SH AUTHOR
Bjorn Benson
.SH DISAPPOINTMENTS
This version runs under 4.2bsd with termcaps only.  Also, the
single flib display should show the "standard" circles and arrows type 
state machine.
