.TH ADDWORD 6
.ad b
.SH NAME
addword - add a word to the hangman database
.SH SYNOPSIS
.B addword
word
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/STANDARD
.TP
Origin:
Hewlett Packard
.SH DESCRIPTION
.I Addword
adds a new word to the hangman database.
.SH AUTHOR
Dave Taylor, Hewlett Packard Colorado Network Operation
.SH BUGS
.I Addword
doesn't check to ensure that the word isn't already
in the database, so it is possible to duplicate.
