.TH HAHGMAN 6
.ad b
.SH NAME
hangman - play the computer in hangman
.SH SYNOPSIS
.B hangman
.SH HP-UX COMPATIBILITY
.TP 10
Level:
HP-UX/STANDARD
.TP
Origin:
Hewlett Packard
.SH DESCRIPTION
.I Hangman
is a macabre rewrite of the classic game of the same
name and is simple to play.
.SH AUTHOR
Dave Taylor, Hewlett Packard Colorado Network Operation
.SH SEE\ ALSO
addword(6)
.SH BUGS
It should be noted that some installations of this
program have databases containing extremely difficult
words to guess!
