.TH LETTER 6
.SH NAME
letter \- pornographic letter generating program
.SH SYNOPSIS
.I /usr/games/letter
.SH DESCRIPTION
.I Letter
is a mindless program which generates dirty letters. (purportedly to the
editor of Penthouse magazine) It works by meandering through a story
outline, filling in slots with words from compiled-in lists.
The result is written to the standard output.
.SH CAVEAT
This program should not be run by anyone who is easily offended.
.SH AUTHOR
You wouldn't admit to having written this program, so I don't see why you
expect someone else to.
.SH FILES
.SH "SEE ALSO"
rogue(6) \- for some good
.I clean
fun.
.SH DIAGNOSTICS
none
.SH BUGS
Output should be run through
.I fmt.
.sp
The nature of the story doesn't vary much, and the choice of words is
rather limited, so it gets boring real quickly.
.sp
Makes grammatical errors, which are sometimes amusing.
.sp
Has no knowledge of human anatomy, so it glibly describes acts which are
physically impossible (or at least very, very improbable).
.sp
Output should be rot13'd.
.sp
You should be ashamed of yourself for running this program. ;-)
