#! /bin/sh
# $Header: /home/Vince/cvs/news.d/rn.d/kitleader,v 1.1 1990-02-26 22:35:59 vrs Exp $
#
# $Log: not supported by cvs2svn $
# Version 1.1  87/12/29  10:32:49  vrs
# Initial version
# 
# Revision 4.3  85/05/01  11:42:03  lwall
# Baseline for release with 4.3bsd.
# 

cat >$1 <<EOT
#! /bin/sh

# Make a new directory for the rn sources, cd to it, and run kits 1 thru $3 
# through sh.  When all $3 kits have been run, read README.

echo "This is rn kit $2 (of $3).  If kit $2 is complete, the line"
echo '"'"End of kit $2 (of $3)"'" will echo at the end.'
echo ""
export PATH || (echo "You didn't use sh, you clunch." ; kill \$\$)
EOT
