#!/bin/sh
# $Header: /home/Vince/cvs/news.d/rn.d/makedist,v 1.1 1990-02-26 22:36:04 vrs Exp $
#
# $Log: not supported by cvs2svn $
# Version 1.1  87/12/29  10:32:53  vrs
# Initial version
# 
# Revision 4.3  85/05/01  11:42:35  lwall
# Baseline for release with 4.3bsd.
# 

rm -f kit*.list
manifake
kitlists
manimake
makekit kit*.list
