#!/bin/sh
# $Header: /home/Vince/cvs/news.d/rn.d/manimake,v 1.1 1990-02-26 22:36:08 vrs Exp $
#
# $Log: not supported by cvs2svn $
# Version 1.1  87/12/29  10:32:57  vrs
# Initial version
# 
# Revision 4.3  85/05/01  11:42:46  lwall
# Baseline for release with 4.3bsd.
# 

: make MANIFEST and MANIFEST.new say the same thing
if test -f MANIFEST.new; then
    cat <<'EOH' > MANIFEST
After all the rn kits are run you should have the following files:

Filename	Kit Description
--------	--- -----------
EOH
    sort MANIFEST.new >.mani
    grep . kit*.list | sed 's/^kit\(.*\)\.list:\$*\(.*\)$/\2 |\1|/' | \
	sort | \
	join -a1 - .mani | \
	awk -F'|' '{printf "%-16s%2s %s\n",$1,$2,$3}' | \
	unexpand >> MANIFEST
    rm .mani
else
    echo "You don't have a MANIFEST.new file.  Run manifake."
fi
