#
# Makefile for atc in distribution directory
#
ALL	= atc
MODEL	= -i
OPTIONS	= -O -DGAMLIB=\"$(GAMLIB)
include ../../../CONFIG
CURSESLIBR =	libatc.a
OFILE =		tunable.o
CFILE =		tunable.c

atc:		$(CURSESLIBR) $(OFILE)
		$(CC) $(CFLAGS) $(OFILE) $(CURSESLIBR) -o $@ $(LIBS)

preserve:	
		rm tunable.c
		cp tunable.n tunable.c
