#
# Makefile for atc in distribution directory
#

LIBS =		-lm -lx # -ll
CURSESLIBS =	-lcurses -ltermcap $(LIBS)

CURSESLIBR =	libatc.a

OFILE =		tunable.o

CFILE =		tunable.c

CFLAGS =	-O -i

all:		atc

atc:		$(CURSESLIBR) $(OFILE)
		$(CC) $(CFLAGS) $(OFILE) $(CURSESLIBR) $(CURSESLIBS) -o atc

preserve:	
		rm tunable.c
		cp tunable.n tunable.c
