.TH TTTT 6 "6 March 1990"
.SH NAME
tttt
\- tic-tac-toc-toe with wraparound edges
.SH SYNOPSIS
.B /usr/games/tttt
.SH DESCRIPTION
Tic-Tac-Toc-Toe is a 4 by 4 version of Tic-Tac-Toe
with wraparound edges.  The goal of the game is to
connect 4 of your pieces in a row, either horizontally,
vertically, or diagonally.  Note that diagonal wins can
be off-center, due to the wraparound edges (and hence, there
are no corners in the board).
.PP
To play, simply press the letter and number corresponding
to select the appropriate square, and the computer will then
take its turn.
.PP
The first player to connect four squares in a row wins.  If
the board becomes filled without a winner, it is a tie game.
.SH COMMANDS
.RS
.IP "a-d, 0-4"
Select the row and column for your move.
.IP h
Scroll the board left.
.IP l
Scroll the board right.
.IP k
Scroll the board up.
.IP j
Scroll the board down.
.IP ctrl-L
Redraw the screen.
.IP q
Quit the game.
.RE
.SH HISTORY
This program was originally written for an Advanced Logic
Design class, as a high level version of the program to
later be implemented in hardware.  It was converted to run
with curses in an attempt to procrastinate working on the
hardware implementation.
.SH AUTHOR
Eric Lechner, lechner@ucscb.ucsc.edu
