#
#	Utilities
#
ALL	= giftogs$(EXE) scr2gs$(EXE) gsrot$(EXE) gs2xbm$(EXE) px2xbm$(EXE) \
	  scrtoppm$(EXE) xbmshrink$(EXE) xbmbrev$(EXE) xbm2imp$(EXE)
include $(HOME)/CONFIG
.SUFFIXES: .bm .gs .scr .uu .imp .uunet
CFLAGS	= -g

all install:	$(ALL)

clean:
	rm -f $(ALL)
