#! /bin/csh -f
set rcfile=~/.calrc remtime="" movo="" movc="" mov="" remc="" noglob
if (x$1 != x) set rcfile = $1
/bin/echo -n "Flags [<ra1mxd] "
set flgs = $<
while ("$flgs" == '?' || "$flgs" == )
	/bin/echo "Flags:"
	/bin/echo "< - use alternate dates file" 
	/bin/echo "r - remind at certain time"
	/bin/echo "a - print always during period"
	/bin/echo "1 - print once during period" ; /bin/echo "m - send mail"
	/bin/echo "x - execute program - a,1 say how often"
	/bin/echo "d - delete when finished" ; /bin/echo ""
	/bin/echo -n "Flags [ra1mxd] " ; set flgs = $<
end
/bin/echo $flgs | grep -s "<"
if ($status == 0) then
	/bin/echo -n "Alternate file: "; set altfile = $<
	while ("$altfile" == '?' || "$altfile" == )
		/bin/echo "The alternate file will be used as another dates file."
		/bin/echo -n "Alternate file: "; set altfile = $<
	end
	/bin/echo "<	$altfile"
	/bin/echo "<	$altfile" >> $rcfile
	exit 0
endif
/bin/echo $flgs | grep -s "r"
if ($status == 0) then
	/bin/echo -n "Remind time [hhmm]: " ; set remc = " " remtime = $<
	while ("$remtime" == '?')
		/bin/echo "Remind expects a four digit time, i.e. 2330."
		/bin/echo -n "Remind time [hhmm]: " ; set remtime = $<
	end
endif
/bin/echo $flgs | grep -s "d"
if ($status == 1) then
	/bin/echo -n "Move forward [+<num>]: "
	set movc = "" mov = $< 
	while ("$mov" == '?')
		/bin/echo "Enter months and days, eg: +3m2d, +14d, +1m"
		/bin/echo -n "Move forward [+<num>]: "
		set mov = $< 
	end
	/bin/echo $mov | egrep -s "^\+"
	if ($status == 1) then
		if ("$mov" != no && "$mov" != n && "$mov" != ) /bin/echo "bad date - $mov."
		set mov = ""
	endif
	if ("$mov" != ) set movo = "+" movc = " "
endif
/bin/echo -n "Start date: " ; set date1 = $<
while ("$date1" == '?')
	/bin/echo "Enter starting date; default is '*'"
	/bin/echo -n "Start date: " ; set date1 = $<
end
if ("$date1" == ) set date1 = "*"
/bin/echo -n "End date: " ; set date2 = $<
while ("$date2" == '?')
	/bin/echo "Enter ending date; default is '*'"
	/bin/echo -n "End date: " ; set date2 = $<
end
if ("$date2" == ) set date2 = "*"
if ("$date1$date2" == "**") then
	/bin/echo "No dates given."
	exit 1
endif
/bin/echo $flgs | grep -s "x"
if ($status == 0) then
	set cmd
	/bin/echo -n "Command: "
else
	/bin/echo -n "Message: "
endif
set msg = $<
while ("$msg" == '?' || "$msg" == )
	if ($?cmd) then
		/bin/echo "Enter command to be executed between $date1 and $date2"
		/bin/echo -n "Command: "
	else
		/bin/echo "Any message you want printed between $date1 and $date2"
		/bin/echo -n "Message: "
	endif
	set msg = $<
end
/bin/echo "$flgs$movo	$date1	$date2		$mov$movc$remtime$remc$msg"
/bin/echo "$flgs$movo	$date1	$date2		$mov$movc$remtime$remc$msg" >>$rcfile
